### ISSUE TITLE
Share gist for Regular Expressions and Data Cleaning, Part 1

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/data-cleaning-course#17]
I don't have the correct gist for [this lesson](https://rfortherestofus.com/courses/data-cleaning/lessons/regular-expressions-and-data-cleaning-part-1/). Can you please share the correct URL?

**Comment by luisDVA** [comment]
Here it is!
https://gist.github.com/luisDVA/20ad9b248b5f445d61ba02e2f3a2a591
