### ISSUE TITLE
Fix gt output

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/data-cleaning-course#7]
This is what I'm seeing on line 194 + 195 of 03_Restructuring-Data.Rmd slide:

![image](https://user-images.githubusercontent.com/13971585/104615771-678a2580-563e-11eb-9e9e-8e20429a3cfb.png)

**Comment by dgkeyes** [comment]
Shows up later in this section as well

**Comment by dgkeyes** [comment]
Actually, this is showing up throughout the slides for me.

**Comment by luisDVA** [comment]
these gt objects are what I see when I knit
![image](https://user-images.githubusercontent.com/5580938/104666223-1ca9f580-56b2-11eb-887b-f1deea796ee1.png)
Im on xaringan 0.18.1 but will look into this asap

**Comment by dgkeyes** [comment]
Super weird. I just updated xaringan to 0.19 but still have this issue. FWIW it works for me on the pizza_orders slide in the common issues section, but nowhere else.

**Comment by luisDVA** [comment]
sorted, this recent comment on a xaringan issue explains the problem
https://github.com/yihui/xaringan/issues/293#issuecomment-761973964
