### ISSUE TITLE
Make promo video

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/data-cleaning-course#9]

**Comment by dgkeyes** [comment]
@luisDVA Do you want to try starting a script for the promo video? Feel free to write in a Google Doc and share it with me. Take a look at any of the other courses to see examples of what this video should look like.

**Comment by luisDVA** [comment]
here's a link to the doc with the draft script for the promo
https://docs.google.com/document/d/1Dp-Hxqtj5iP0gT8LdluDEBV--4DpvTe11MpvTNbh1jE/edit?usp=sharing

**Comment by dgkeyes** [comment]
Thanks! I made a bunch of edits. Take a look and let me know if they look ok to you.

**Comment by luisDVA** [comment]
they look great! the text is now much more dynamic and informative!

**Comment by dgkeyes** [comment]
Glad you like them! I'm going to reopen this issue so that you can record the video. Please just record yourself looking into the camera and reading the text. Do as many takes as you want. No need to edit anything yourself. Just say on the video something like, "please use that last take that I did." Then upload the raw video, which I'll share with my video editor. She'll edit the video, adding in snippets from the course material. Let me know if you have any questions!

**Comment by luisDVA** [comment]
sorry for closing the issue. I'll get the recording done asap and put it on the drive folder

**Comment by luisDVA** [comment]
uploaded five different takes to the drive. no particular order or preference, just various attempts at reading the script.

**Comment by dgkeyes** [comment]
Great, just sent them to my video editor!

**Comment by dgkeyes** [comment]
This is almost set. I have a just a couple small tweaks, but you can see the nearly complete version [here](https://drive.google.com/file/d/140o6BDzcvXHYp9DJu2Fg1V3lak5Y97zh/view?usp=sharing).

**Comment by luisDVA** [comment]
Looks great, I like the background music. Can we change the little text under my name? I'm no longer working at that institution. 

Can we aim for something more timeless? My current position as a research associate at a conservation ngo is short term and I'm waiting on results for a separate fellowship, so it would be better to have something institution-independent.

**Comment by dgkeyes** [comment]
Sure, what do you want to have as your title?

**Comment by luisDVA** [comment]
Let's go with something generic like:

"PhD in Biological Sciences, Data Scientist"
or
"Researcher, Zoology"

or anything vague that will still apply even if I keep changing affiliations in the near future

**Comment by luisDVA** [comment]
if it's also not too late, I'd like to have both of my last names on the little text thing. To differentiate myself from my dad (a mathematician who does lots of teaching) and because I'm on board with the 'two-surnames, no-hyphen' movement for Latin American scientists to claim their identity :)

**Comment by dgkeyes** [comment]
Ah, totally! Do you want me to use the two last names on the website as well then? And in all emails?

**Comment by luisDVA** [comment]
As long as the video and the bio section have my full name, feel free to just write Luis Verde to keep things simple in tweets, emails, etc.

**Comment by dgkeyes** [comment]
Ok, sounds good.
